on: push
name: Build and deploy on push
jobs:
  build:
    name: psiace/psiace.github.io
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: shalzz/zola-deploy-action
      uses: shalzz/zola-deploy-action@master
      env:
        PAGES_BRANCH: master
        TOKEN: ${{ secrets.TOKEN }}
        BUILD_FLAGS: --drafts
    - name: jakejarvis/cloudflare-purge-action
      uses: jakejarvis/cloudflare-purge-action@master
      env:
        CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
